#! /usr/bin/env bash


CONTAINER="synapse_web"

source .env


url="https://api.telegram.org/bot$TOKEN/sendMessage"

start_time=$(date +%s)
while true; do

    now_time=$(date +%s)
    elapsed_time=$(( now_time - start_time ))

    if [ "$( docker container inspect -f '{{.State.Running}}' $CONTAINER )" = "false" ]; then
        msg="⚠️$CONTAINER HAS STOPPED!"
        data="{\"chat_id\": \"$CHAT_ID_DEBUG\", \"text\": \"$msg\", \"disable_web_page_preview\": false, \"parse_mode\": \"HTML\"}"

        curl -X POST -H "Content-Type: application/json" -d "$data" "$url"
    fi

    if [[ $elapsed_time -ge 86400 ]]; then  # Health alerts every 24 hours (86400 secs)
        msg="✅$CONTAINER"
        data="{\"chat_id\": \"$CHAT_ID_DEBUG\", \"text\": \"$msg\", \"disable_web_page_preview\": false, \"parse_mode\": \"HTML\"}"

        curl -X POST -H "Content-Type: application/json" -d "$data" "$url"
        start_time=$(date +%s)  # Reset start_time
    fi

    sleep 1800  # Check every 30 mins (1800 secs)
done &
