#! /usr/bin/env bash

set -e

IMAGE_NAME="synapse_web"


# Build Image
echo "Building $IMAGE_NAME"
docker build -f docker/web/Dockerfile . -t $IMAGE_NAME

# Tag Image
docker tag synapse_web eu.gcr.io/hip-orbit-347017/$IMAGE_NAME:latest

# Push Image to GCP
docker push eu.gcr.io/hip-orbit-347017/$IMAGE_NAME:latest
